---

- name: Honolulu Cat
  hosts: all
  gather_facts: False
  become: true
  vars:
    hostname: honolulu-cateyes
    tz: America/Honolulu
    token: T04NJ722U/BQB4MBBHV/RZPNWsz38MD1WtuVcena5reb
    
  tasks:
    - name: Set timezone to "{{ tz }}"
      timezone:
        name: "{{ tz }}"
    - name: Display new timezone
      shell: date +%Z 
      
